#!/bin/bash

# This script must be sourced:
# source files-manage.sh


clean_bash_history() {
    clear
    local tmp_history
    tmp_history=$(mktemp)

    grep -vE '(curl|chmod|^\s*\./|echo)' ~/.bash_history > "$tmp_history"
    mv "$tmp_history" ~/.bash_history

    history -c
    history -r
}

clean_bash_history


run_cmd() {
    # Execute command
    eval "$1"

    # Add only the real command to history
    history -s "$1"
}


clear


run_cmd "lab start files-manage"


# SSH command is executed normally
run_cmd "ssh student@servera"


# Server operations
run_cmd "mkdir Music Pictures Videos"

run_cmd "touch song1.mp3 song2.mp3 song3.mp3 song4.mp3 song5.mp3 song6.mp3"

run_cmd "touch snap1.jpg snap2.jpg snap3.jpg snap4.jpg snap5.jpg snap6.jpg"

run_cmd "touch film1.avi film2.avi film3.avi film4.avi film5.avi film6.avi"

run_cmd "mv song1.mp3 song2.mp3 song3.mp3 song4.mp3 song5.mp3 song6.mp3 Music"

run_cmd "mv snap1.jpg snap2.jpg snap3.jpg snap4.jpg snap5.jpg snap6.jpg Pictures"

run_cmd "mv film1.avi film2.avi film3.avi film4.avi film5.avi film6.avi Videos"


run_cmd "mkdir friends family work"


run_cmd "cd friends"

run_cmd "cp ~/Music/song1.mp3 ~/Music/song2.mp3 ~/Pictures/snap1.jpg ~/Pictures/snap2.jpg ~/Videos/film1.avi ~/Videos/film2.avi ."


run_cmd "cd ../family"

run_cmd "cp ~/Music/song3.mp3 ~/Music/song4.mp3 ~/Pictures/snap3.jpg ~/Pictures/snap4.jpg ~/Videos/film3.avi ~/Videos/film4.avi ."


run_cmd "cd ../work"

run_cmd "cp -r ~/family ~/friends ."


run_cmd "cd .."

run_cmd "rm -r family friends work"


# Verify lab
run_cmd "lab grade files-manage"


# Finish lab
run_cmd "lab finish files-manage"


# Save history permanently
history -w
